{
 "title": "IntelliScale Monitoring",
 "time": { "from": "2025-04-26T21:22:46.800Z", "to": "2025-04-26T23:23:56.484Z" },
 "refresh": "5s",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "## IntelliScale by Sahith Aitha"
   }
  },
  {
   "title": "Flask-app RAM usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"flask-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask-Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"flask-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask-app CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"flask-app\"}[1m]) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "RL-Agent status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "up{job=\"rl-agent\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RL-agent CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"rl-agent\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}